### GET request hello
GET localhost:8080/response/hello

### GET request random
GET localhost:8080/response/random

### GET request message
GET localhost:8080/response/message

### GET request complex message
GET localhost:8080/response/test

### GET request complex message
GET localhost:8080/response/map

### GET request complex message
GET localhost:8080/response/image

### GET request complex message
GET localhost:8080/response/entity
